config/routes.rb
Atelier::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  post "/surveys/question_groups/:question_group_id/answer_groups" => "custom_answer_groups#create", :as => nil
  mount Rapidfire::Engine => "/surveys"

  resources :folders do
    post "/sort" => "folders#sort", on: :collection, as: :sort
  end
  get "projects/search" => "projects#search", as: :search_projects
  get "projects/tagged/:tag" => "projects#tag_index", as: :tag
  resources :projects do
    resources :critiques do
      post "/like" => "critiques#like", :as => "like"
      post "/dislike" => "critiques#dislike", :as => "dislike"
      post "/rate/:rating" => "critiques#rating", :as => "rating"
      get "/redline" => "critiques#redline"
      resources :responses 
    end
    post "/sort" => "projects#sort", on: :collection, as: :sort
  end
  get "/critiques/new/none" => "critiques#new_none", as: "new_none_critiques"
  get "/critiques/tutorial" => "critiques#tutorial", as: "tutorial_critiques"
  post "/critiques/tutorial_check" => "critiques#tutorial_check", as: "tutorial_check_critiques"
  get "/critiques/rate" => "critiques#rate", as: "rate_critiques"
  devise_for :users
  resources :users

  get "/about", to: "pages#about"
  get "/dashboard", to: "pages#dashboard"
  get "/consent", to: "pages#consent"

  root :to => "pages#dashboard"

end

app/views/rapidfire/questions/_form.html.erb
<h3>Question</h3>

<%= form_for [@question_group, question] do |f| %>
  <%- unless question.errors.empty? %>
    <ul>
      <%- question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :type %>
  <%= f.select :type, ::Rapidfire::QuestionForm::QUESTION_TYPES, {}, id: "question_type" %>

  <%= f.label :question_text %>
  <%= f.text_field :question_text %>

  <%= f.label :answer_options %>
  <%= f.text_area :answer_options, rows: 5 %>

  <h4>Other options</h4>
  <hr/>

  <%= f.label :answer_presence %>
  <%= f.check_box :answer_presence %>

  <%= f.label :answer_minimum_length %>
  <%= f.text_field :answer_minimum_length %>

  <%= f.label :answer_maximum_length %>
  <%= f.text_field :answer_maximum_length %>

  <%= f.label :answer_greater_than_or_equal_to %>
  <%= f.text_field :answer_greater_than_or_equal_to %>

  <%= f.label :answer_less_than_or_equal_to %>
  <%= f.text_field :answer_less_than_or_equal_to %>

  <%= f.submit %>
<% end %>

app/views/rapidfire/questions/_question.html.erb
<tr id="question_<%= question.id %>">
  <td><%= question.question_text %></td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Edit", [:edit, question.question_group, question] %></li>
      <li><%= link_to "Delete", [question.question_group, question], method: :delete %></li>
    </ul>
  </td>
</tr>

app/views/rapidfire/questions/edit.html.erb
<%= render partial: 'form', locals: {question: @question} %>

app/views/rapidfire/questions/index.html.erb
<h2>
  Questions
  <%= link_to "New Question", new_question_group_question_path(@question_group) %>
</h2>
<hr/>

<table>
  <colgroup>
    <col>
    <col width="250">
  </colgroup>
  <thead>
    <tr>
      <th>Question</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question", collection: @questions %>
  </tbody>
</table>

app/views/rapidfire/questions/new.html.erb
<%= render partial: 'form', locals: {question: @question} %>