config/routes.rb
Atelier::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  post "/surveys/question_groups/:question_group_id/answer_groups" => "custom_answer_groups#create", :as => nil
  mount Rapidfire::Engine => "/surveys"

  resources :folders do
    post "/sort" => "folders#sort", on: :collection, as: :sort
  end
  get "projects/search" => "projects#search", as: :search_projects
  get "projects/tagged/:tag" => "projects#tag_index", as: :tag
  resources :projects do
    resources :critiques do
      post "/like" => "critiques#like", :as => "like"
      post "/dislike" => "critiques#dislike", :as => "dislike"
      post "/rate/:rating" => "critiques#rating", :as => "rating"
      get "/redline" => "critiques#redline"
      resources :responses 
    end
    post "/sort" => "projects#sort", on: :collection, as: :sort
  end
  get "/critiques/new/none" => "critiques#new_none", as: "new_none_critiques"
  get "/critiques/tutorial" => "critiques#tutorial", as: "tutorial_critiques"
  post "/critiques/tutorial_check" => "critiques#tutorial_check", as: "tutorial_check_critiques"
  get "/critiques/rate" => "critiques#rate", as: "rate_critiques"
  devise_for :users
  resources :users

  get "/about", to: "pages#about"
  get "/dashboard", to: "pages#dashboard"
  get "/consent", to: "pages#consent"

  root :to => "pages#dashboard"

end

app/models/folder.rb
require 'format'

class Folder < ActiveRecord::Base
  belongs_to :user
  has_many :projects
  has_many :critiques, through: :projects
  attr_accessible :name, :description, :user_id

  validates_presence_of :name
  validates_presence_of :description

  def self.get_order_clause(order_by)
    case order_by
    when "alphabetical"
      "name"
    when "recentcreated"
      "created_at DESC"
    when "recentupdated"
      "updated_at DESC"
    when "lowprojects"
      "projects_count ASC"
    when "highprojects"
      "projects_count DESC"
    when "lowcritiques"
      "critiques_count ASC"
    when "highcritiques"
      "critiques_count DESC"
    else
      ""
    end
  end

  def self.get_all(order_by)
    Folder.order(order_by) 
  end

  def self.get_mentoring(order_by, user)
    Folder.joins(:projects => :critiques).where("critiques.user_id = ?", user.id).uniq.order(order_by)
  end

  def self.get_recommended(order_by, user)
    @folders = Folder.joins(:user).where("users.id <> ? AND (users.skill_level = ? OR users.skill_level = ?)", user.id, user.skill_level.id, user.skill_level.lower_tier.id).order(order_by)
    @folders - self.get_mentoring(order_by, user)
  end

  def self.get_by_user(order_by, user)
    Folder.joins(:user).where("users.id = ?", user.id).order(order_by)
  end

  def is_mentored_by?(user) 
    @folders = Folder.joins(:projects => :critiques).where("critiques.user_id = ?", user.id).uniq
    @folders.include? self
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
  end

  def show
    @folder = Folder.find(params[:id])
  end

  def new
    @folder = Folder.new
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def create
    @folder = Folder.new(params[:folder])
    @folder.user_id = current_user.id

    respond_to do |format|
      if @folder.save
        # Add projects to this folder
        @picked_projects = params[:project]
        if !@picked_projects.nil?
          @picked_projects.each_key do |key|
            project = Project.find(key)
            project.folder_id = @folder.id
            project.save
          end
        end

        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        # Reset the projects that were added to this folder
        @proj = Project.where(:folder_id => @folder.id)
        @proj.each {|p| p.folder_id = nil; p.save}

        # Add projects to folder
        @picked_projects = params[:project]
        if !@picked_projects.nil?
          @picked_projects.each_key do |key|
            p = Project.find(key)
            p.folder_id = @folder.id
            p.save
          end
        end

        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: "Folder was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def sort
    @order_by = params[:order_by]
    @scope = params[:scope]
    @user = User.find_by_username(params[:username]) if !params[:username].nil?

    @order_clause = Project.get_order_clause(@order_by)

    if @scope == "all"
      @projects = Project.get_all(@order_clause)
    elsif @scope == "mentoring"
      @projects = Project.get_mentoring(@order_clause, current_user)
    elsif @scope == "recommended"
      @projects = Project.get_recommended(@order_clause, current_user)
    elsif @scope == "users"
      @projects = Project.get_by_user(@order_clause, @user)
    end

    respond_to do |format|
      format.js
    end
  end
end

app/views/folders/_folder.html.erb
<% show_name = true if local_assigns[:show_name].nil? %>

<tr class="project">
  <td>
    <div class="pull-left">
      <div class="project-link">
        <h3><%= link_to folder.name, folder %></h3>
        <p><%= truncate(folder.description, length: 60) %></p>
      </div>
      <div class="project-info">
        <span class="<%= 'text-danger' if folder.critiques.count == 0 %>">
          <strong><%= pluralize folder.critiques.count, "critique" %></strong>
        </span> &sdot;
        <%= pluralize folder.projects.count, "project" %></strong> &sdot;
        last updated <%= time_ago_in_words folder.updated_at %> ago
        <% if show_name %>
          <br />
          by <%= folder.user.username %> <%= skill_level_badge(folder.user.skill_level) %>
        <% end %>
      </div>
    </div>
      <div class="pull-right project-actions">
        <% if folder.is_mentored_by? current_user %>
          <%= link_to folder, class: "btn", disabled: "disabled" do %>
            <%= fa_icon "star" %>
            Mentoring
          <% end %>
        <% elsif folder.user.id != current_user.id %>
          <%= link_to folder, class: "btn btn-primary" do %>
            <%= fa_icon "star" %>
            Mentor
          <% end %>
        <% elsif show_name %>
          <%= link_to "Your folder", folder, class: "btn", disabled: "disabled" %>
        <% end %>
      </div>
    <div class="clearfix"></div>
  </td>
</tr>

app/views/folders/_folder_list.html.erb
<table class="table project-list table-bordered">
  <tr class="header">
    <th>
      <%= pluralize folders.count, "folder" %>
    </th>
  </tr>
  <%= render partial: "folders/folder", collection: folders, locals: { :show_name => show_name } %>
</table>

app/views/folders/_form.html.erb
<%= form_for [@folder] do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Folder Name", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.text_area :description, size: "20x3", placeholder: "Briefly describe this folder.", class: "form-control" %>
  </div>
  <div class="field folders-entries-choose panel panel-default">
    <div class="panel-heading">
      <p>
        Choose <strong>projects</strong> to include in this folder:
        <br />
        <small class="text-muted">
          Adding an project already inside a different folder will move it out of its original folder.  
        </small>
      </p>
    </div>
    <div class="panel-body">
      <table>
        <% current_user.projects.each do |project| %>
          <tr>
            <td class="entry-name">
              <label>
                <input type="checkbox" name="project[<%= project.id %>]" value="<%= project.id %>" <%= !@folder.new_record? && (project.folder == @folder) ? "checked": "" %> />
              </label>
              
              <%= link_to project.title, project %>
            </td>
            <td class="folder-label">
              <% if !project.folder.nil? %>
                <div class="label label-info">
                  Folder: <%= project.folder.name %>
                </div>
              <% else %>
                <div class="label label-default">
                  No folder
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="actions">
    <%= f.submit button_name, class: "btn btn-default" %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<%= render "projects/header" %>
<h1>Edit Project Details</h1>

<%= render "form", button_name: "Save" %>

app/views/folders/new.html.erb
<h1>New Folder</h1>
<p>
Create a folder to group related projects together.
</p>
<%= render 'form', button_name: "Create" %>

app/views/folders/show.html.erb
<% if can? :manage, @folder%>
<div class="project-actions pull-right">
  <%= link_to new_project_path, class: "btn btn-primary" do %>
    <%= fa_icon "plus" %>
    New Project
  <% end %>
  
  <%= link_to edit_folder_path(@folder), class: "btn" do %>
    <%= fa_icon "pencil" %>
    Edit
  <% end %>
  <%= link_to folder_path(@folder), method: :delete, confirm: "Are you sure you want to delete this folder? This action cannot be undone.", class: "btn" do %>
    <%= fa_icon "times" %>
    Delete
  <% end %>
</div>
<% end %>

<div class="project-header">
  <h1>
    <%= @folder.name %>
    <small>
      by <%= link_to @folder.user.username, @folder.user %> <%= skill_level_badge(@folder.user.skill_level) %>
    </small>
  </h1>
</div>
<p class="lead"><%= @folder.description %></p>

<hr />

<% if @folder.projects.count <= 0 %>
  No projects for this folder yet.
<% else %>
  <%= render 'projects/entry_list', :projects => @folder.projects %>
<% end %>