config/routes.rb
Atelier::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  post "/surveys/question_groups/:question_group_id/answer_groups" => "custom_answer_groups#create", :as => nil
  mount Rapidfire::Engine => "/surveys"

  resources :folders do
    post "/sort" => "folders#sort", on: :collection, as: :sort
  end
  get "projects/search" => "projects#search", as: :search_projects
  get "projects/tagged/:tag" => "projects#tag_index", as: :tag
  resources :projects do
    resources :critiques do
      post "/like" => "critiques#like", :as => "like"
      post "/dislike" => "critiques#dislike", :as => "dislike"
      post "/rate/:rating" => "critiques#rating", :as => "rating"
      get "/redline" => "critiques#redline"
      resources :responses 
    end
    post "/sort" => "projects#sort", on: :collection, as: :sort
  end
  get "/critiques/new/none" => "critiques#new_none", as: "new_none_critiques"
  get "/critiques/tutorial" => "critiques#tutorial", as: "tutorial_critiques"
  post "/critiques/tutorial_check" => "critiques#tutorial_check", as: "tutorial_check_critiques"
  get "/critiques/rate" => "critiques#rate", as: "rate_critiques"
  devise_for :users
  resources :users

  get "/about", to: "pages#about"
  get "/dashboard", to: "pages#dashboard"
  get "/consent", to: "pages#consent"

  root :to => "pages#dashboard"

end

app/views/rapidfire/question_groups/_form.html.erb
<h3><%= question_group.new_record? ? "New Group" : "Edit Group" %></h3>

<%= form_for question_group do |f| %>
  <%- if question_group.errors.any? %>
    <ul>
      <%- question_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/rapidfire/question_groups/_question_group.html.erb
<tr id= "question_group_<%= question_group.id %>">
  <td>
    <% if can_administer? %>
      <%= link_to question_group.name, question_group_questions_path(question_group) %>
    <% else %>
      <%= question_group.name %>
    <% end %>
  </td>
  <td>
    <ul class="horizontal-list">
      <li><%= link_to "Answer Questions", new_question_group_answer_group_path(question_group) %></li>
      <% if can_administer? %>
        <li><%= link_to "Results", [:results, question_group] %></li>
        <li><%= link_to "Delete", [question_group], method: :delete %></li>
      <% end %>
    </ul>
  </td>
</tr>

app/views/rapidfire/question_groups/index.html.erb
<h2>
  Question Groups
  <% if can_administer? %>
    <%= link_to "New Group", new_question_group_path %>
  <% end %>
</h2>
<hr/>

<table>
  <colgroup>
    <col>
    <col width="250">
  </colgroup>
  <thead>
    <tr>
      <th>Question Group</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question_group", collection: @question_groups %>
  </tbody>
</table>

app/views/rapidfire/question_groups/new.html.erb
<%= render partial: 'form', locals: {question_group: @question_group} %>

app/views/rapidfire/question_groups/results.html.erb
<h1>Results</h1>

<%- @question_group_results.each do |result| %>
  <div>
    <h4><%= result.question.question_text %></h4>
    <p>
      <%- if result.results.is_a?(Array) %>
        <ol>
          <%- result.results.each do |answer| %>
            <li><%= answer %></li>
          <% end %>
        </ol>
      <% elsif result.results.is_a?(Hash) %>
        <table>
          <thead>
            <tr>
              <th>Option</th>
              <th>Count</th>
            </tr>
          </thead>
          <tbody>
            <%- result.results.each do |option, count| %>
              <tr>
                <td><%= option %></td>
                <td><%= count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
  </div>
<% end %>