config/routes.rb
Atelier::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  post "/surveys/question_groups/:question_group_id/answer_groups" => "custom_answer_groups#create", :as => nil
  mount Rapidfire::Engine => "/surveys"

  resources :folders do
    post "/sort" => "folders#sort", on: :collection, as: :sort
  end
  get "projects/search" => "projects#search", as: :search_projects
  get "projects/tagged/:tag" => "projects#tag_index", as: :tag
  resources :projects do
    resources :critiques do
      post "/like" => "critiques#like", :as => "like"
      post "/dislike" => "critiques#dislike", :as => "dislike"
      post "/rate/:rating" => "critiques#rating", :as => "rating"
      get "/redline" => "critiques#redline"
      resources :responses 
    end
    post "/sort" => "projects#sort", on: :collection, as: :sort
  end
  get "/critiques/new/none" => "critiques#new_none", as: "new_none_critiques"
  get "/critiques/tutorial" => "critiques#tutorial", as: "tutorial_critiques"
  post "/critiques/tutorial_check" => "critiques#tutorial_check", as: "tutorial_check_critiques"
  get "/critiques/rate" => "critiques#rate", as: "rate_critiques"
  devise_for :users
  resources :users

  get "/about", to: "pages#about"
  get "/dashboard", to: "pages#dashboard"
  get "/consent", to: "pages#consent"

  root :to => "pages#dashboard"

end

app/models/project.rb
require 'format'

class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :folder, :counter_cache => true, :touch => true
  has_many :critiques, :dependent => :destroy
  attr_accessible :title, :content, :user_id, :folder_id, :image, :doneness, :tag_list

  validates_presence_of :title

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'Your attachment is the wrong file type. Only jpeg/jpg/png/gif images are allowed.'
  validates_attachment_presence :image

  acts_as_taggable
  is_impressionable

  def self.get_order_clause(order_by)
    case order_by
    when "alphabetical"
      "title"
    when "recentcreated"
      "created_at DESC"
    when "recentupdated"
      "updated_at DESC"
    when "lowcritiques"
      "critiques_count ASC"
    when "highcritiques"
      "critiques_count DESC"
    else
      ""
    end
  end

  def self.get_mentoring(order_by, user)
    Project.joins(:critiques).where("critiques.user_id = ?", user.id).uniq.order(order_by)
  end

  def self.get_recommended(order_by, user)
    @projects = Project.joins(:user).where("users.id <> ? AND (users.skill_level_id = ? OR users.skill_level_id = ?)", user.id, user.skill_level.id, user.skill_level.lower_tier.id).order(order_by)
    @projects - self.get_mentoring(order_by, user)
  end

  def self.get_by_user(order_by, user)
    Project.where("user_id = ?", user.id).order(order_by)
  end

  # Gets the project after this one in the list of recommended projects for the
  # current user. Returns nil if it reaches the end of the list.
  def recommended_next(user)
    if Atelier::Application.config.skill_levels
      @recommended = Project.get_recommended(Project.get_order_clause("lowcritiques"), user)
    else
      @recommended = Project.order(Project.get_order_clause("lowcritiques"))
    end
    index = @recommended.index(self)
    @recommended[index + 1]
  end

  def created_at_formatted
    self.created_at.strftime("%m-%d-%Y %I:%M%p")
  end

  def critique_options(limit = 5)
    Critique.joins(:project).where(["projects.user_id = ? AND critiques.created_at < ?", self.user.id, self.created_at]).order("critiques.created_at").limit(limit)
  end

  def is_mentored_by?(user) 
    @projects = Project.joins(:critiques).where("critiques.user_id = ?", user.id).uniq
    @projects.include? self
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  skip_before_filter :authenticate_user!, :only => :show
  load_and_authorize_resource
  skip_authorize_resource :only => :show
  impressionist

  def index
    @order_clause = "critiques_count"
    @projects = Project.order(@order_clause)
    @mentoring_projects = Project.get_mentoring(@order_clause, current_user)
    @rec_projects = Project.get_recommended(@order_clause, current_user)
  end

  def show
    @project = Project.find(params[:id])
    @critique = Critique.new
    
    @project.critiques.each do |c|
      impressionist(c, "critique-project-view")
    end
  end

  def new
    @project = Project.new
    @critique_options = current_user.recent_critiques_received
  end

  def edit
    @project = Project.find(params[:id])
    @critique_options = @project.critique_options
  end

  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to rate_critiques_path, notice: 'Project was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: "Project was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def tag_index
    @order_clause = "critiques_count"
    @tag = params[:tag]
    @projects = Project.order(@order_clause).tagged_with(@tag)
  end

  def search
    @query = params[:search]
    @projects = Project.tagged_with(@query, :any => true)
  end

  def sort
    @scope = params[:scope]
    @order_by = params[:order_by]
    @order_clause = Project.get_order_clause(@order_by)
    @user = User.find_by_username(params[:username]) if !params[:username].nil?
    @show_name = (@scope != "users")

    if @scope == "all"
      @projects = Project.order(@order_clause)
    elsif @scope == "mentoring"
      @projects = Project.get_mentoring(@order_clause, current_user)
    elsif @scope == "recommended"
      @projects = Project.get_recommended(@order_clause, current_user)
    elsif @scope == "users"
      @projects = Project.get_by_user(@order_clause, @user)
    elsif @scope == "tagged"
      @tag = params[:tag]
      @projects = Project.order(@order_clause).tagged_with(params[:tag])
    elsif @scope == "search"
      @query = params[:search]
      @projects = Project.order(@order_clause).tagged_with(@query, :any => true)
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def doneness_text(doneness)
    case doneness
    when "study-exercise"
      "Study/Exercise"
    when "sketch"
      "Quick Sketch"
    when "wip"
      "Work-in-progress"
    when "finished"
      "Finished Work"
    else
      ""
    end
  end
  
  def skill_level_badge(skill_level)
    if Atelier::Application.config.skill_levels
      case skill_level.name_key.to_sym
      when :beginner
        badge_type = "label-warning"
      when :intermediate
        badge_type = "label-info"
      when :advanced
        badge_type = "label-success"
      else
        badget_type = "table-default"
      end
      "<span class='label #{badge_type}'>#{skill_level.name_key.titleize}</span>".html_safe
    end
  end
end

app/views/projects/_body.html.erb
<div class="project-info pull-left">
  <h1><%= @project.title %></h1>
  <% if !@project.doneness.nil? %>
    <p>
    <em>
      <%= doneness_text(@project.doneness) %>
    </em>
    </p>
  <% end %>
  <p>
    by <%= link_to @project.user.username, @project.user %> <%= skill_level_badge(@project.user.skill_level) %>
  </p>
</div>

<div class="project-actions pull-right">
  <% if can? :manage, @project %>
    <%= link_to edit_project_path(@project), class: "btn" do %>
      <%= fa_icon "pencil" %>
      Edit
    <% end %>
    <%= link_to project_path(@project), method: :delete, confirm: "Are you sure you want to delete this project? This action cannot be undone.", class: "btn" do %>
      <%= fa_icon "times" %>
      Delete
    <% end %>
<% end %>
</div>

<div style="clear:both"></div>

<div class="project-image">
  <%= image_tag(@project.image.url, class: "small", crossOrigin: "anonymous") if !@project.image_file_name.nil? %>
</div>

<div>
  <% if @project.content == "" %>
    <p class="text-muted">
      <em>Hmm, this project doesn't seem to have any content.</em>
    </p>
  <% else %>
    <%= Format.markdown @project.content %>
  <% end %>
</div>
<p class="project-tags text-muted">
<% @project.tag_list.each do |tag| %>
  <span class="tag">
    <%= link_to "##{tag}", tag_path(tag) %>
  </span>
<% end %>
</p>

<script>
  $(document).ready(function() {
    $(".project-image img").click(function() {
      $(this).toggleClass("small");
    });
  });
</script>

app/views/projects/_entry_list.html.erb
<h3><%= pluralize projects.count, "project" %></h3>

<table class="table table-striped">
  <% projects.each do |project| %>
    <tr>
      <td><strong><%= link_to project.title, project_path(project) %></strong></td>
      <td><%= link_to "View project", project_path(project) %></td>
      <td>created <%= time_ago_in_words project.created_at %> ago</td>
      <td><%= pluralize project.critiques.count, "critique" %> received</td>
    </tr>
  <% end %>
</table>

app/views/projects/_form.html.erb
<%= form_for @project, validate: false do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "Project Title", class: "largely" %>
  </div>
  <div class="field form-group">
    <%= f.label :image, class: "image-label" %>
    <%= f.file_field :image, class: "hidden" %>
    <button class="project-browse-image btn btn-default">Choose file</button>
    <span id="project-file-name">
      <% if @project.image_file_name.nil? %>
        <em>No file chosen</em>
      <% else %>
        <%= @project.image_file_name %>
      <% end %>
    </span>
  </div>
  <div class="field form-group">
    <label for="project_doneness">How finished is your project? <small class="text-muted">This will let others know what kind of feedback you want.</small></label>
    <select id="project_doneness" name="project[doneness]" class="form-control">
      <option value="study-exercise"><%= doneness_text "study-exercise" %></option>
      <option value="sketch"><%= doneness_text "sketch" %></option>
      <option value="wip"><%= doneness_text "wip" %></option>
      <option value="finished"><%= doneness_text "finished" %></option>
    </select>
  </div>
  <div class="field form-group">
    <%= f.text_area :content, size: "20x10", placeholder: "Describe your project, point out what you're struggling with,  and give yourself a critique to give others something to base their critiques on...", data: {provide: "markdown"} %>
  </div>
  <div class="field form-group">
    <%= f.text_field :tag_list, placeholder: "Tags (separated by commas)", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit button_name, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_header.html.erb
<% if !@folder.nil? %>
<div class="page-header back-to-folder">
  <%= link_to @folder do %>
    &larr;
    Back to folder
  <% end %>
</div>
<% end %>

app/views/projects/_new_steps.html.erb
<ul class="new-project-progress">
  <li class="<%= 'active' if active_step >= 1 %>">Post New Project</li>
  <li class="<%= 'active' if active_step >= 2 %>">Rate Critiques</li>
  <li class="<%= 'active' if active_step >= 3 %>">Write Critiques</li>
</ul>

app/views/projects/_project.html.erb
<% show_name = true if local_assigns[:show_name].nil? %>

<tr class="project">
  <td>
    <div class="project-thumbnail pull-left">
      <% if !project.image_file_name.nil? %>
        <%= link_to project do %>
          <%= image_tag project.image.url %>
        <% end %>
      <% end %>
    </div>
    <div class="pull-left">
      <div class="project-link">
        <h3><%= link_to project.title, project  %></h3>
        <p><%= truncate(project.content, length: 60) %></p>
      </div>
      <div class="project-info">
        <span class="<%= 'text-danger' if project.critiques.count == 0 %>">
          <strong><%= pluralize project.critiques.count, "critique" %></strong>
        </span> &sdot;
        <% if !project.doneness.nil? %>
          <%= doneness_text project.doneness %> &sdot;
        <% end %>
        last updated <%= time_ago_in_words project.updated_at %> ago
        <% if show_name %>
          <br />
          by <%= link_to project.user.username, project.user %> <%= skill_level_badge(project.user.skill_level) %>
        <% end %>
      </div>
    </div>
      <div class="pull-right project-actions">
        <% if project.is_mentored_by? current_user %>
          <%= link_to project, class: "btn", disabled: "disabled" do %>
            <%= fa_icon "star" %>
            Mentoring
          <% end %>
        <% elsif project.user.id != current_user.id %>
          <%= link_to project, class: "btn btn-primary" do %>
            <%= fa_icon "star" %>
            Mentor
          <% end %>
        <% elsif show_name %>
          <%= link_to "Your project", project, class: "btn", disabled: "disabled" %>
        <% end %>
      </div>
    <div class="clearfix"></div>
  </td>
</tr>

app/views/projects/_project_list.html.erb
<% show_name = true if local_assigns[:show_name].nil? %>
<% show_header = true if local_assigns[:show_header].nil? %>
<% scope = "all" if local_assigns[:scope].nil? %>
<% order_by = "lowcritiques" if local_assigns[:order_by].nil? %>

<div class="project-list-container">
<%= form_tag sort_projects_path, remote: true, class: "sort-projects form-group pull-right" do %>
  <label>
    Sort by 
  </label>
  <%= select_tag :order_by, options_for_select([
    ["Alphabetical", "alphabetical"],
    ["Newest", "recentcreated"],
    ["Most Recently Updated", "recentupdated"],
    ["Lowest to Highest Critiques", "lowcritiques"],
    ["Highest to Lowest Critiques", "highcritiques"]
  ], order_by), class: "form-control" %>
  <%= hidden_field_tag :scope, scope %>
  <% if @tag %>
    <%= hidden_field_tag :tag, @tag %>
  <% end %>
  <% if @query %>
    <%= hidden_field_tag :search, @query %>
  <% end %>
  <% if scope == "users" %>
    <%= hidden_field_tag :username, @user.username %> 
  <% end %>
<% end %>
<table class="table project-list <%= "table-bordered" if show_header %>">
  <% if show_header %>
    <tr class="header">
      <th>
        <%= pluralize projects.count, "project" %>
      </th>
    </tr>
  <% end %>
  <%= render partial: "projects/project", collection: projects, locals: { :show_name => show_name } %>
</table>
</div>

app/views/projects/edit.html.erb
<%= render 'header' %>
<%= render 'form', button_name: "Save" %>

app/views/projects/index.html.erb
<h1>Mentor a Project</h1>
<p>
To mentor a project, view the page corresponding to the project and <strong>write a critique</strong>.
</p>

<div class="project-index row">
  <ul class="nav nav-stacked nav-pills col-md-3">
    <% if Atelier::Application.config.skill_levels %>
      <li class="active"><a href="#recommended" data-toggle="tab">Recommended</a></li>
    <% end %>
    <li class="<%= "active" if !Atelier::Application.config.skill_levels %>"><a href="#mentoring" data-toggle="tab">Projects You're Mentoring</a></li>
    <li><a href="#all" data-toggle="tab">All</a></li>
  </ul>

  <div class="tab-content col-md-9">
    <% if Atelier::Application.config.skill_levels %>
      <div class="tab-pane recommended active" id="recommended">
        <p>Because you are a <strong><%= current_user.skill_level %></strong> user, we recommend you mentor projects by <strong><%= current_user.skill_level %></strong> <% if SkillLevel.levels[current_user.skill_level.name_key.to_sym] != 0 %>and <strong><%= current_user.skill_level.lower_tier %></strong><% end %> users.</p>

        <% if @rec_projects.nil? || @rec_projects.count <= 0 %>
          <p class="text-muted">
          <em>You have no recommended projects yet. Check back as people post!</em>
          </p>
        <% else %>
          <%= render "projects/project_list", projects: @rec_projects, scope: "recommended" %>
        <% end %>
      </div>
    <% end %>

    <div class="tab-pane mentoring <%= "active" if !Atelier::Application.config.skill_levels %>" id="mentoring">
      <% if @mentoring_projects.nil? || @mentoring_projects.count <= 0 %>
        <p class="text-muted">
        <em>You are not mentoring any projects.</em>
        </p>
      <% else %>
        <%= render "projects/project_list", projects: @mentoring_projects, scope: "mentoring" %>
      <% end %>
    </div>

    <div class="tab-pane all" id="all">
      <% if @projects.nil? || @projects.count <= 0 %>
        <p class="text-muted">
        <em>There aren't any projects yet.</em>
        </p>
      <% else %>
        <%= render "projects/project_list", projects: @projects %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'header' %>
<%= render 'projects/new_steps', active_step: 1 %>

<h1>Post a Project</h1>

<p>
Receive mentoring by creating projects you want help with. A project should represent a learning goal that you want to achieve. This could range from skill-related things like "Learn how to draw cats" to more "meta" projects like "Prepare for a tabling at a conference".
</p>

<p>
<strong>Example Project:</strong> <a href="http://atelier-stanford.herokuapp.com/projects/8">Improve my figure drawing skills</a>
</p>
<hr />

<% if current_user.skill_level.lowest? && !current_user.tutorial_done? %>
  <em>You have not yet completed the <%= link_to "Beginner's critiquing tutorial", tutorial_critiques_path %>. You need to complete the tutorial before you're able to post projects.</em>
<% else %>
  <%= render 'form', button_name: "Create" %>
<% end %>

app/views/projects/search.html.erb
<h1>Search Results for "<%= @query %>"</h1>
<div class="search">
  <% if @projects.empty? %>
    We didn't find any projects tagged with your query! Remember, you can search for multiple tags at once by separating tags by commas. 
  <% else %>
    <%= render "projects/project_list", projects: @projects, scope: "search" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= render 'projects/header' %>

<%= render 'projects/body' %>

<h3><%= pluralize @project.critiques.count, "Critique" %></h3>

<% if @project.critiques.count <= 0 %>
  <p>
    No critiques yet.
  </p>
<% else %>
  <%= render partial: "critiques/critique", collection: @project.critiques.order(:created_at) %>
<% end %>

<% if current_or_guest_user.id != @project.user.id %>
  <h3>Add a Critique</h3>
<% end %>
<%= render "critiques/form" %>

app/views/projects/tag_index.html.erb
<h1>#<%= @tag %></h1>
<div class="tagged">
  <%= render "projects/project_list", projects: @projects, scope: "tagged" %>
</div>